// request constants
export const REQUEST_INIT = 'REQUEST_INIT';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const REQUEST_NOT_FOUND = 'REQUEST_NOT_FOUND';
export const REQUEST_TIMEOUT = 'REQUEST_TIMEOUT';
export const DOWNLOAD_ERROR = 'DOWNLOAD_ERROR';

//Merchant Management actiontypes
export const SELECT_ALL_MERCHANTS = 'SELECT_ALL_MERCHANTS';
export const FETCH_MERCHANT_SUCCESS = 'FETCH_MERCHANT_SUCCESS';
export const SELECT_MERCHANT = 'SELECT_MERCHANT';

//Publisher Management actiontypes
export const SELECT_ALL_PUBLISHERS = 'SELECT_ALL_PUBLISHERS';
export const FETCH_PUBLISHER_SUCCESS = 'FETCH_PUBLISHER_SUCCESS';
export const SELECT_PUBLISHER = 'SELECT_PUBLISHER';
export const SET_BLACKLIST_REASON = 'SET_BLACKLIST_REASON';
export const SET_BLACKLIST_STATUS = 'SET_BLACKLIST_STATUS';

//publisher bank info
export const FETCH_PUBLISHERS_BANKS = 'FETCH_PUBLISHERS_BANKS';
export const FETCH_PUBLISHER_BANK_HISTORY ='FETCH_PUBLISHER_BANK_HISTORY';
export const FETCH_PUBLISHER_BANK_INFO = 'FETCH_PUBLISHER_BANK_INFO';
export const PUBLISHER_BANK_VERIFICATION = 'PUBLISHER_BANK_VERIFICATION';

//reports
export const FETCH_DAILY_FLASH_REPORT_SUCCESS = 'FETCH_DAILY_FLASH_REPORT_SUCCESS';
export const FETCH_MONTLY_FLASH_REPORT_SUCCESS = 'FETCH_MONTLY_FLASH_REPORT_SUCCESS';
export const FETCH_DAILY_MERCHANT_KPI_REPORT_SUCCESS = 'FETCH_DAILY_MERCHANT_KPI_REPORT_SUCCESS';
export const FETCH_MONTLY_MERCHANT_KPI_REPORT_SUCCESS = 'FETCH_MONTLY_MERCHANT_KPI_REPORT_SUCCESS';
export const FETCH_ORDER_REPORT_SUCCESS = 'FETCH_ORDER_REPORT_SUCCESS';

// reset report filters constants
export const RESET_MERCHANT_FILTERS = 'RESET_MERCHANT_FILTERS';
export const RESET_PUBLISHER_FILTERS = 'RESET_PUBLISHER_FILTERS';

//modal state
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SET_TITLE = 'SET_TITLE';

//loader
export const DISMISS_LOADER = 'DISMISS_LOADER';
